
spring.application.name=taxform
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/eztaxpostgres_utf8
spring.datasource.username=postgres
spring.datasource.password=p@ssw0rd
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.initialization-mode=always
spring.datasource.platform=postgresql

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

logging.level.org.springframework.jdbc.core=DEBUG
logging.level.com.ez.taxform=DEBUG
